export const ADMIN_SIGNUP_SUCCESS="ADMIN_SIGNUP_SUCCESS"
export const ADMIN_SIGNUP_ERROR="ADMIN_SIGNUP_ERROR"
export const ADMIN_SIGNUP_REQUEST="ADMIN_SIGNUP_REQUEST"
export const ADMIN_SIGNUP_ERROR_HANDLE="ADMIN_SIGNUP_ERROR_HANDLE"

export const ADMIN_SIGNIN_REQUEST="ADMIN_SIGNIN_REQUEST"
export const ADMIN_SIGNIN_SUCCESS="ADMIN_SIGNIN_SUCCESS"
export const ADMIN_SIGNIN_ERROR="ADMIN_SIGNIN_ERROR"

export const ADMIN_LOGOUT_REQUEST = "ADMIN_LOGOUT_REQUEST";
export const ADMIN_LOGOUT_ERROR="ADMIN_LOGOUT_ERROR"
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS";


export const ADMIN_RESET_PASSWORD_SUCCESS = 'ADMIN_RESET_PASSWORD_SUCCESS';
export const ADMIN_RESET_PASSWORD_ERROR = 'ADMIN_RESET_PASSWORD_ERROR';
export const ADMIN_RESET_PASSWORD_REQUEST = 'ADMIN_RESET_PASSWORD_REQUEST';

export const ADMIN_FORGOT_PASSWORD_SUCCESS="ADMIN_FORGOT_PASSWORD_SUCCESS";

