export const USER_SIGNUP_SUCCESS="USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_ERROR="USER_SIGNUP_ERROR"
export const USER_SIGNUP_REQUEST="USER_SIGNUP_REQUEST"
export const USER_SIGNUP_ERROR_HANDLE="USER_SIGNUP_ERROR_HANDLE"

export const USER_SIGNIN_REQUEST="USER_SIGNIN_REQUEST"
export const USER_SIGNIN_SUCCESS="USER_SIGNIN_SUCCESS"
export const USER_SIGNIN_ERROR="USER_SIGNIN_ERROR"

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_ERROR="USER_LOGOUT_ERROR"
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS";
export const USER_FORGOT_PASSWORD_SUCCESS="USER_FORGOT_PASSWORD_SUCCESS"