export const USER_GETSTOCKS_SUCCESS="USER_GETSTOCKS_SUCCESS"
export const USER_GETSTOCKS_ERROR="USER_GETSTOCKS_ERROR"
export const USER_GETSTOCKS_REQUEST="USER_GETSTOCKS_REQUEST"

export const USER_GETSINGLESTOCK_SUCCESS="USER_GETSINGLESTOCK_SUCCESS"
export const USER_GETSINGLESTOCK_ERROR="USER_GETSINGLESTOCK_ERROR"
export const USER_GETSINGLESTOCK_REQUEST="USER_GETSINGLESTOCK_REQUEST"

export const ADD_FUNDS_SUCCESS="ADD_FUNDS_SUCCESS"
export const ADD_FUNDS_ERROR="ADD_FUNDS_ERROR"
export const ADD_FUNDS_REQUEST="ADD_FUNDS_REQUEST"