export const STOCK_GET_REQUEST="STOCK_GET_REQUEST"
export const STOCK_GET_SUCCESS="STOCK_GET_SUCCESS"
export const STOCK_GET_ERROR="STOCK_GET_ERROR"

export const ALLSTOCK_GET_REQUEST="ALLSTOCK_GET_REQUEST"
export const ALLSTOCK_GET_SUCCESS="ALLSTOCK_GET_SUCCESS"
export const ALLSTOCK_GET_ERROR="ALLSTOCK_GET_ERROR"

export const STOCK_ADD_REQUEST="STOCK_ADD_REQUEST"
export const STOCK_ADD_SUCCESS="STOCK_ADD_SUCCESS"
export const STOCK_ADD_ERROR="STOCK_ADD_ERROR"

export const STOCK_DELETE_REQUEST="STOCK_DELETE_REQUEST"
export const STOCK_DELETE_SUCCESS="STOCK_DELETE_SUCCESS"
export const STOCK_DELETE_ERROR="STOCK_DELETE_ERROR"

export const STOCK_UPDATE_REQUEST="STOCK_UPDATE_REQUEST"
export const STOCK_UPDATE_SUCCESS="STOCK_UPDATE_SUCCESS"
export const STOCK_UPDATE_ERROR="STOCK_UPDATE_ERROR"