export const ADMIN_SIGNUP_SUCCESS="SIGNUP_SUCCESS"
export const ADMIN_SIGNUP_ERROR="SIGNUP_ERROR"
export const ADMIN_SIGNUP_REQUEST="SIGNUP_REQUEST"
export const ADMIN_SIGNUP_ERROR_HANDLE="SIGNUP_ERROR_HANDLE"

export const ADMIN_SIGNIN_REQUEST="SIGNIN_REQUEST"
export const ADMIN_SIGNIN_SUCCESS="SIGNIN_SUCCESS"
export const ADMIN_SIGNIN_ERROR="SIGNIN_ERROR"

export const ADMIN_LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const ADMIN_LOGOUT_ERROR="SIGNIN_ERROR"
export const ADMIN_LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
